version: "3"

networks:
  ethernet:
    external: true

services:
  gl-mail-grpc-server-golang:
    container_name: gl-mail-grpc-server-golang
    image: gl-mail-grpc-server-golang
    build:
      context: .
      dockerfile: .docker/golang/dev/Dockerfile
    env_file:
      - ./.docker/golang/dev/.env
    links:
      - gl-mail-grpc-server-mysql
    depends_on:
      - gl-mail-grpc-server-mysql
    ports:
      - 50051:50051
    networks:
      - ethernet

  gl-mail-grpc-server-mysql:
    container_name: gl-mail-grpc-server-mysql
    image: gl-mail-grpc-server-mysql
    build: .docker/mysql/dev
    env_file:
      - ./.docker/mysql/dev/.env
    networks:
      - ethernet