version: "3"

networks:
  grpc-1:
    driver: bridge

services:
  gl-mail-grpc-server-golang:
    container_name: gl-mail-grpc-server-golang
    image: gl-mail-grpc-server-golang
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    env_file:
      - ./.docker/golang/.env
    links:
      - gl-mail-grpc-server-mysql
    depends_on:
      - gl-mail-grpc-server-mysql
    ports:
      - 50051:50051
    networks:
      - grpc-1

  gl-mail-grpc-server-mysql:
    container_name: gl-mail-grpc-server-mysql
    image: gl-mail-grpc-server-mysql
    build: .docker/mysql
    env_file:
      - ./.docker/mysql/.env
    networks:
      - grpc-1