version: "3"

networks:
  ethernet:
    external: true

services:
  gl-mail-grpc-server-golang:
    container_name: gl-mail-grpc-server-golang
    image: chapal/gl-mail-grpc-server-golang:v1
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    env_file:
      - ./.docker/golang/.env
    links:
      - gl-mail-grpc-server-mysql
    depends_on:
      - gl-mail-grpc-server-mysql
    ports:
      - 50051:50051
    networks:
      - ethernet

  gl-mail-grpc-server-mysql:
    container_name: gl-mail-grpc-server-mysql
    image: chapal/gl-mail-grpc-server-mysql:v1
    build: .docker/mysql
    env_file:
      - ./.docker/mysql/.env
    networks:
      - ethernet