apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-mail-grpc-server-golang-deployment
  labels:
    app: gl-mail-grpc-server
spec:
  selector:
    matchLabels:
      app: gl-mail-grpc-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gl-mail-grpc-server
    spec:
      containers:
      - name: gl-mail-grpc-server-golang
        image: chapal/gl-mail-grpc-server-golang:v1
        ports:
        - name: gl-service
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: gl-mail-grpc-server-golang-service
spec:
  type: NodePort
  selector:
    app: gl-mail-grpc-server
  ports:
  - port: 50051
    targetPort: gl-service