apiVersion: v1
kind: Pod
metadata:
  name: gl-mail-grpc-server-go-pod
  labels:
    name: gl-mail-grpc-server-go-pod
spec:
  containers:
  - name: golang
    image: chapal/gl-mail-grpc-server-golang:v1
    ports:
    - containerPort: 50051
    env:
    - name: DB_SOURCE
      value: "test:test@tcp(gl-mail-grpc-server-mysql:3306)/test?parseTime=true"
    - name: APP_ENV
      value: "dev"
    - name: SERVER_SOURCE
      value: ":50051"
---
kind: Service
apiVersion: v1
metadata:
  name: gl-mail-grpc-server-golang
  labels:
    name: gl-mail-grpc-server-golang
spec:
  type: LoadBalancer
  selector:
    name: gl-mail-grpc-server-go-pod
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051