apiVersion: v1
kind: Pod
metadata:
  name: gl-mail-grpc-server-golang-pod
  labels:
    app: gl-mail-grpc-server
spec:
  containers:
  - name: gl-mail-grpc-server-golang
    image: chapal/gl-mail-grpc-server-golang:v1
    ports:
    - containerPort: 50051
    env:
    - name: SERVER_SOURCE
      value: ":50051"
    - name: DB_SOURCE
      value: "test:test@tcp(gl-mail-grpc-server-mysql-service:3306)/test?parseTime=true"
    - name: APP_ENV
      value: "dev"