apiVersion: v1
kind: Pod
metadata:
  name: gl-mail-grpc-server-mysql-pod
  labels:
    name: gl-mail-grpc-server-mysql-pod
spec:
  containers:
  - name: gl-mail-grpc-server-mysql
    image: chapal/gl-mail-grpc-server-mysql:v1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    - name: MYSQL_DATABASE
      value: "test"
    - name: MYSQL_USER
      value: "test"
    - name: MYSQL_PASSWORD
      value: "test"
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: gl-mail-grpc-server-mysql-volume
---
apiVersion: v1
kind: Service
metadata:
  name: gl-mail-grpc-server-mysql
  labels:
    name: gl-mail-grpc-server-mysql
spec:
  ports:
  - port: 3306
  selector:
    name: gl-mail-grpc-server-mysql-pod
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gl-mail-grpc-server-mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
